#App
server:
  port: 8080
  error:
    include-binding-errors: always
spring:
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  banner:
    location: classpath:banner.txt
#  main:
#    allow-circular-references: true